### ISSUE TITLE
Search functionality 

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/tiwun-awesome#12]
Go for it boy <3

**Comment by Alir3z4** [comment]
is this done @amirm3hdi ?

**Comment by amirm3hdi** [comment]
Fixed 8d3a86b59fbdeadb7c4e5e406c26d8a6a3b407e5

**Comment by Alir3z4** [comment]
> Fixed 8d3a86b

Can't believe you did it once in your whole life
