### ISSUE TITLE
Items don't have their Author URL 

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/tiwun-awesome#21]
There's nothing!

Have a look at:
http://tiwun.com/items/4668dd00-ea9d-11e4-9cd3-00dbc7650003/

Author URL is:
http://tiwun.com/users///

**Comment by amirm3hdi** [comment]
Because of ui-sref attr...
Template variables don't work there sometimes

**Comment by Alir3z4** [comment]
They should work usually,
Find the issue and as the master once said, "Fix It!"

It's annoying to see them act like that.
In matter of fact none of them have the author url set, at least as far as I see.

**Comment by amirm3hdi** [comment]
When I was losing hope, I fixed the comment author links, and that got fixed too...
It's pretty dumb to not work because one other ui-sref is missing a param...

**Comment by Alir3z4** [comment]
@amirm3hdi Nice, care to share the commit ?

**Comment by amirm3hdi** [comment]
Committed and pushed to master.

**Comment by Alir3z4** [comment]
Found it, thanks ;)

**Comment by amirm3hdi** [comment]
Nope, I changed it to author and it returns empty...

**Comment by Alir3z4** [comment]
Yep, and we have a buggy change on master.
Use branches **BITCH**

![bitch](http://www.omega-level.net/wp-content/uploads/2013/01/BRO-IM-FEELING-YOU.1.png)

**Comment by Alir3z4** [comment]
Anyway, try to see if the item from API comes with user id and stuff

**Comment by Alir3z4** [comment]
Ok I have fixed for you
Just push now <3
