### ISSUE TITLE
Oh... No item found for #accessories!

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/tiwun-awesome#24]
How to reproduce:
* Open http://tiwun.com/tags/accessories/
* Click on `load more` couple of times
* instead of not loading more items, it shows `Oh... No item found for #accessories!`

**Comment by amirm3hdi** [comment]
Ops

**Comment by Alir3z4** [comment]
Double whoops :|

**Comment by Alir3z4** [comment]
This is very gud man =))
